FROM continuumio/miniconda3:latest

# Install extra packages if required
RUN apt-get update && apt-get install -y \
    xxxxxx \
    && rm -rf /var/lib/apt/lists/*

# Add the user that will run the app (no need to run as root)
RUN groupadd -r cmelab && useradd -r -g cmelab cmelab

WORKDIR /app

# Install myapp requirements
COPY conda_env.yml /app/conda_env.yml
RUN conda config --add channels conda-forge \
    && conda env create -n epoxpy -f conda_env.yml \
    && rm -rf /opt/conda/pkgs/*

# Install myapp
COPY . /app/
RUN chown -R cmelab:cmelab /app/*

# activate the myapp environment
ENV PATH /opt/conda/envs/epoxpy/bin:$PATH

RUN ll