image: continuumio/miniconda3

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - echo "Default pipeline."
          - ls
  branches:
    master:
      - step:
          script:
            - echo "This script runs only on commit to the master branch."
            - ls
    freud_integration:
      - step:
          script:
            - echo "This script runs only on commit to freud_integration branch"
<<<<<<< HEAD
            - ls
            - conda env create -f conda_env.yml
            - source activate epoxy_sim
            - cd epoxpy
            - pytest
    signac_integration:
      - step:
          script:
            - echo "This script runs only on commit to signac_integration branch"
            - ls
            - conda env create -f conda_env.yml
            - source activate epoxpy_env 
            - cd epoxpy
            - pytest

=======
            - ls
>>>>>>> c3b67c8032a5a7b4bc87463a5ab7b347cefb34af
