name: epoxpy_env
channels:
- mosdef
- omnia
- conda-forge
- glotzer
- defaults
dependencies:
- python
- hoomd
- mbuild
- freud
- matplotlib
- gsd
- pytest
- signac
- signac-flow



















































































































