name: epoxy_sim
channels:
- mosdef
- omnia
- conda-forge
- glotzer
- defaults
dependencies:
- python=2.7
- hoomd
- mbuild
- freud
- matplotlib
- gsd




















































































































