name: epoxpy_env
channels:
- mosdef
- omnia
- conda-forge
- glotzer
- cmelab
- defaults
dependencies:
- python=3.5
- numpy
- mbuild=0.6.1
- freud
- matplotlib
- hoomd_dybond
- gsd
- pytest
- signac
- signac-flow



















































































































