{% set name = "epoxpy" %}
{% set version = "2.0.2" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  path: ../ 

requirements:
  channels:
    - glotzer
    - mosdef
    - omnia
    - conda-forge
    - bioconda
  build:
    - python
    - pytest
    - matplotlib
    - numpy
    - mbuild 0.6.1
    - hoomd
  run:
    - python
    - pytest
    - matplotlib
    - numpy
    - mbuild 0.6.1
    - hoomd

test:
  imports:
    - epoxpy

about:
  home: https://bitbucket.org/cmelab/epoxpy
  license: GPL-3.0 
  license_file: LICENSE
